version: '3.8'

services:
  #---------------------ORDER_SERVICE_ENVIRONMENT---------------------------
  order-service:
    build: .
    container_name: order-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-postgres-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATA_REDIS_HOST=order-redis-cache
      - SPRING_DATA_REDIS_PORT=6379

      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - APPLICATION_CONFIG_USER_URL=http://user-service:8080
    depends_on:
      order-postgres-db:
        condition: service_healthy
      order-redis-cache:
        condition: service_healthy

  order-postgres-db:
    image: postgres:16-alpine
    container_name: order-postgres-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - order-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  order-redis-cache:
    image: redis:7-alpine
    container_name: order-redis-cache
    ports:
      - "6380:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  #---------------------USER_SERVICE_ENVIRONMENT---------------------------
  user-service:
    build: ../user-service
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-postgres-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATA_REDIS_HOST=user-redis-cache
      - SPRING_DATA_REDIS_PORT=6379

      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
    depends_on:
      user-postgres-db:
        condition: service_healthy
      user-redis-cache:
        condition: service_healthy

  user-postgres-db:
    image: postgres:16-alpine
    container_name: user-postgres-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - user-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5


  user-redis-cache:
    image: redis:7-alpine
    container_name: user-redis-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  #---------------------AUTH_SERVICE_ENVIRONMENT---------------------------
#
#  auth-service:
#    build: ../authentication-service
#    container_name: auth-service
#    ports:
#      - "8081:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-postgres-db:5432/${POSTGRES_DB}
#      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
#      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
#
#      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
#      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
#    depends_on:
#      auth-postgres-db:
#        condition: service_healthy
#
#  auth-postgres-db:
#    image: postgres:16-alpine
#    container_name: auth-postgres-db
#    environment:
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    ports:
#      - "5433:5432"
#    volumes:
#      - auth-postgres-data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

volumes:
  order-postgres-data:
  user-postgres-data:
#  auth-postgres-data: